http:
  port:         8080
  maxHeaderBytes:  1  # MegaBytes
  readTimeout:    30  # Seconds
  writeTimeout:   30  # Seconds
  requestTimeout: 20  # Seconds

auth:
  tokenExpTime:   15  # Minutes
  refreshExpTime:  7  # Days

mail:
  host:         smtp.gmail.com
  port:         "587"
  subject:      "Email Verification"
  tokenExpTime: 30 # Days

queue:
  user: guest
  password: guest
  host: localhost
  port: 5672
  name: Astral